### ISSUE TITLE
images with fractional pixel dimensions fail

### ISSUE THREAD

**Issue by bwidawsk** [skorokithakis/lektor-thumbnail-generator#5]
I think this is an Inkscape specific problem (sorry) since I doubt the other formats support fractional dimensions...

When calculating the ratio, apparently the fractions are causing issues. I think `source_width // source_height` might fix the problem, but I'm too lazy to check and just modified my images instead :1st_place_medal: 

```
E 2015/9/gen-graphics-and-the-urb/packing.svg (TypeError: unsupported operand type(s) for /: 'NoneType' and 'NoneType')
  Traceback (most recent call last):
    File "/usr/lib/python3.9/site-packages/lektor/builder.py", line 800, in update
      yield ctx
    File "/usr/lib/python3.9/site-packages/lektor/builder.py", line 1070, in build_artifact
      build_func(artifact)
    File "/home/bwidawsk/.cache/lektor/packages/f051825033487973eef8bb5d951a28f7/lektor_thumbnail_generator.py", line 81, in build_artifact
      _, height = compute_dimensions(width, None, w, h)
    File "/usr/lib/python3.9/site-packages/lektor/imagetools.py", line 462, in compute_dimensions
      source_ratio = source_width / source_height
  TypeError: unsupported operand type(s) for /: 'NoneType' and 'NoneType'
```

**Comment by bwidawsk** [comment]
I don't believe there's a reasonable way to fix this directly from the plugin. The fix is required in lektor itself. get_image_info() doesn't seem to do the right thing.

Closing
